name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          docker pull potesala/youtube-whisper
          docker tag potesala/youtube-whisper r8.im/poteitoo/youtube-whisper
          docker push r8.im/poteitoo/youtube-whisper
          
